#!/bin/bash

set -o errexit   # abort on nonzero exitstatus
set -o pipefail  # don't hide errors within pipes

# shellcheck disable=SC1091
source /afs/ifh.de/group/cta/scratch/prado/MC-VERITAS/util.sh

atm="winter"
zenith="20"
wobble="0.25"
mode="std"
nsb_group="b"
n_min=0    # min run
n_max=10000   # max run (100000) 

# shellcheck disable=SC2068
collect_arguments 7 atm zenith wobble mode nsb_group n_min n_max $@

all_n=$(seq "${n_min}" "${n_max}")

atm=$(validate_atm "${atm}")
zenith=$(validate_zenith "${zenith}")
wobble=$(validate_wobble "${wobble}")
mode=$(validate_mode "${mode}")
nsb_list=$(nsb_list_from_group "${nsb_group}")

bad_runs="lists/care_runs_Zd${zenith}_${atm}_wobble${wobble}_bad.lis"
true > "${bad_runs}"

sec_list=""

sec_file="time.lis"
true > "${sec_file}"

for i in ${all_n}; do
    run=$(compute_run "${zenith}" "${i}")

    for nsb in ${nsb_list}; do
        care_file=$(care_file "${run}" "${zenith}" "${atm}" "${wobble}" "${nsb}" "${mode}")
        if [ ! -f "${care_file}.vbf" ]; then
            printf "Not found file: %s %s\n" "${run}" "${nsb}"
            echo "${run}" >> "${bad_runs}"
            break
        fi        
    done

    first_nsb=$(echo ${nsb_list} | awk '{print $1}')
    log_out=$(care_log "${run}" "${zenith}" "${atm}" "${wobble}" "${first_nsb}" "${mode}" "out")
    if [ -f "${log_out}" ]; then

        sec=$(grep "Seconds:" "${log_out}" | awk '{print $NF}' || true)

        if [ "${sec}" != "" ]; then
            sec_list="$sec_list $sec"
            echo "${sec}" >> "${sec_file}"
        else
            echo "Aborted ${run}"     
        fi
    fi

done

sum=0
n=0
smax=0
smin=10000000000000
for s in ${sec_list}; do
    sum=$(( sum + s ))   
    n=$(( n + 1 ))
    smax=$(( smax > s ? smax : s ))
    smin=$(( smin > s ? s : smin ))
done

mean=$(( sum / n ))

echo   "==========="
printf "Runtime for %s jobs \n" "$n" 
printf "Average: "
TZ=UTC0 printf '%(%H:%M:%S)T\n' "$mean"
printf "Min: "
TZ=UTC0 printf '%(%H:%M:%S)T\n' "$smin"
printf "Max: "
TZ=UTC0 printf '%(%H:%M:%S)T\n' "$smax"
echo   "==========="
