#!/bin/bash

source /afs/ifh.de/group/cta/scratch/prado/MC-DESY/util.sh

atm="winter"
zenith="20"
mode="std"
wobble_list="0.0 0.25 0.5 0.75 1.0 1.25 1.5 1.75 2.0"
nsb_list="50 75 100 130 160 200 250 300 350 400 450"

atm=$(validate_atm "${atm}")
zenith=$(validate_zenith "${zenith}")
mode=$(validate_mode "${mode}")


for wobble in ${wobble_list}; do
    wobble=$(validate_wobble "${wobble}")

    for nsb in ${nsb_list}; do
        care_file=$(compressed_care_file "${zenith}" "${atm}" "${wobble}" "${nsb}" "${mode}")
        if [ -f "${care_file}" ]; then
            printf "File:%s\n" "${care_file}"
            # do something here
        else
            printf "File not found:%s\n" "${care_file}"
        fi

    done

done
