#!/bin/bash

set -o errexit   # abort on nonzero exitstatus
set -o pipefail  # don't hide errors within pipes

SECONDS=0

echo "Starting splitCARE"

show_help() {
    echo ""
    echo "Syntax: ./splitCARE [ -arg value ]"
    echo "Options:"
    echo "-src                                    (source directory)"
    echo "-zenith                                 (zenith angle)"
    echo "-wobble                                 (wobble)"
    echo "-atm                                    (summer/62 or winter/61)"
    echo "-nsb                                    (list of NSB levels)"
    echo "-mode                                   (std or rhv)"
    echo "-n_files                                ()"
    echo ""
}

atm="winter"
zenith="20"     
wobble="0.25"
mode="std"
nsb="200"

while :; do
    case $1 in
        -h|-\?|--help)
            show_help
            exit
            ;;
        -src)
            source_dir=$2
            shift
            ;;
        -zenith)
            zenith=$2
            shift
            ;;
        -wobble)
            wobble=$2
            shift
            ;;
        -atm)
            atm=$2
            shift
            ;;
        -nsb)
            nsb=$2
            shift
            ;;
        -mode)
            mode=$2
            shift
            ;;
        -n_files)
            n_files=$2
            shift
            ;;
        *)
            break
    esac
    shift
done

echo "Source:${source_dir}"

# shellcheck disable=SC1091,SC1090
source "${source_dir}/util.sh"
# shellcheck disable=SC1091,SC1090
source "${source_dir}/setupMC.sh"

atm=$(validate_atm "${atm}")
zenith=$(validate_zenith "${zenith}")
wobble=$(validate_wobble "${wobble}")
mode=$(validate_mode "${mode}")

merged_care_file=$(merged_care_file "${zenith}" "${atm}" "${wobble}" "${nsb}" "${mode}")

cd $(dirname "${merged_care_file}")

if [ ! -f  "${merged_care_file}" ]; then 
    echo "Uncompressing files"

    if [ -f "${merged_care_file}.bz2" ]; then
        bzip2 -dk "${merged_care_file}.bz2"
    elif [ -f "${merged_care_file}.zst" ]; then
        zstd -d  "${merged_care_file}.zst"
    else
        error_exit "Input CARE file not found"
    fi

fi

echo "Splitting ..."
printf "%s\n" "${merged_care_file}"

# shellcheck disable=SC2086
# ${SW_DIR}/eventDisplay/v501_rd/bin/splitVBF "${merged_care_file}" "${n_files}" 1 "${wobble}"
${SW_DIR}/eventDisplay/v501_rd/bin/splitVBF "${merged_care_file}" "${n_files}" 1

print_runtime "${SECONDS}"
