#!/bin/bash

set -o errexit   # abort on nonzero exitstatus
set -o pipefail  # don't hide errors within pipes

echo "Starting subCARE"

# shellcheck disable=SC1091,SC1090
source "util.sh"

atm="summer"
zenith=""
wobble=""
mode="std"
nsb_group=""
n_min=0         # min run
n_max=200001     # max run (100000) 
source_dir=${PWD}
readonly runs_per_job=100
readonly do_submit="true"
readonly force="false"
readonly n_mail=1

# shellcheck disable=SC2068
collect_arguments 7 atm zenith wobble mode nsb_group n_min n_max $@

all_n=$(seq "${n_min}" "${n_max}")
# all_n="25075"
# all_n="87700"

atm=$(validate_atm "${atm}")
zenith=$(validate_zenith "${zenith}")
wobble=$(validate_wobble "${wobble}")
mode=$(validate_mode "${mode}")
nsb_list=$(nsb_list_from_group "${nsb_group}")
# nsb_list="250"

njobs=0
nruns=0
runs=""
first_run=""
# shellcheck disable=SC2086
last_n=$(echo ${all_n} | awk '{print $NF}')
for n in ${all_n}; do
    run=$(compute_run "${zenith}" "${n}")
    if [ "${first_run}" = "" ]; then
        first_run="${run}"
    fi

    gro_file=$(groptics_file "${run}" "${zenith}" "${atm}" "${wobble}")
    if [ ! -f "${gro_file}" ]; then
        # printf "GrOptics file for run %s does not exist - skipping\n" "${run}"
        continue
    fi

    do_run="false"
    for nsb in ${nsb_list}; do
        care_file=$(care_file "${run}" "${zenith}" "${atm}" "${wobble}" "${nsb}" "${mode}")
        if [ -f  "${care_file}.vbf" ] && [ "${force}" = "true" ]; then
            printf "Removing existing file for wobble %s and run %s and NSB %s\n" "${wobble}" "${run}" "${nsb}"
            remove_file "${care_file}.vbf" "${care_file}.root" || true
            do_run="true"
        elif [ ! -f  "${care_file}" ]; then
            do_run="true"
        fi        
    done
    
    if [ "${do_run}" = "true" ]; then
        runs="${runs} ${run}"
        nruns=$(( nruns + 1 ))
    fi        

    if [ "${nruns}" = "${runs_per_job}" ] || [ "${n}" = "${last_n}" ]; then
        send_mail=""
        if [ "${njobs}" -lt "${n_mail}" ]; then
            send_mail="-m ae" # splitting is necessary
        fi

        # shellcheck disable=SC2086
        first_nsb=$(echo ${nsb_list} | awk '{print $1}')
        log_err=$(care_log "${first_run}" "${zenith}" "${atm}" "${wobble}" "${first_nsb}" "${mode}" "err")
        log_out=$(care_log "${first_run}" "${zenith}" "${atm}" "${wobble}" "${first_nsb}" "${mode}" "out")
        remove_file "${log_err}" "${log_out}" || true
        mkdir -p "$(dirname "${log_out}")"
        # chgrp -R veritas "$(dirname "${log_out}")"

        printf "Submitting runs: %s\n" "${runs}" >> "${log_out}"
        
        if [ "${do_submit}" = "true" ]; then
            # shellcheck disable=SC2086
            qsub -P veritas -l s_cpu=23:59:00 -l h_rss=1G ${send_mail} -N "care_${wobble}" -e "${log_err}" \
                -o "${log_out}" "${source_dir}/runCARE" -run "${runs}" -zenith "${zenith}" -atm "${atm}" \
                -wobble "${wobble}" -mode "${mode}" -nsb "${nsb_list}" -src "${source_dir}"
        fi
        
        nruns=0
        runs=""
        njobs=$(( njobs + 1 ))
        first_run=""
    fi
done
