#!/bin/bash

/afs/ifh.de/group/cta/scratch/prado/MC-VERITAS/subCARE -wobble 2.0 -nsb_group a
/afs/ifh.de/group/cta/scratch/prado/MC-VERITAS/subCARE -wobble 2.0 -nsb_group b
/afs/ifh.de/group/cta/scratch/prado/MC-VERITAS/subCARE -wobble 2.0 -nsb_group c

