#!/bin/bash

set -o errexit   # abort on nonzero exitstatus
set -o pipefail  # don't hide errors within pipes

echo "Starting subMerge"

# shellcheck disable=SC1090,SC1091
source "util.sh"

atm="winter"
zenith="20"
wobble="0.5"
mode="std"
nsb_group="a"
n_max=10001
source_dir=${PWD}

# shellcheck disable=SC2068
collect_arguments 6 atm zenith wobble mode nsb_group n_max $@

atm=$(validate_atm "${atm}")
zenith=$(validate_zenith "${zenith}")
wobble=$(validate_wobble "${wobble}")
mode=$(validate_mode "${mode}")
nsb_list=$(nsb_list_from_group "${nsb_group}")

for nsb in ${nsb_list}; do
    send_mail="-m ae" # splitting is necessary
    log_err=$(merged_care_log "${zenith}" "${atm}" "${wobble}" "${nsb}" "${mode}" "err")
    log_out=$(merged_care_log "${zenith}" "${atm}" "${wobble}" "${nsb}" "${mode}" "out")
    remove_file "${log_err}" "${log_out}" || true
    mkdir -p "$(dirname "${log_out}")"

    # shellcheck disable=SC2086
    qsub -P veritas -l s_cpu=48:00:00 -l h_rss=4G ${send_mail} -N "merge_${wobble}" -e "${log_err}" -o "${log_out}" "${source_dir}/mergeCARE" -zenith "${zenith}" -atm "${atm}" -wobble "${wobble}" -mode "${mode}" -nsb "${nsb}" -n_max "${n_max}" -src "${source_dir}"
done
