#!/bin/bash

set -o errexit   # abort on nonzero exitstatus
set -o pipefail  # don't hide errors within pipes

echo "Starting subEvndisp"

show_help() {
    echo ""
    echo "Syntax: ./subEvndisp [ -arg value ]"
    echo "Options:"
    echo "-zenith                                 (zenith angle)"
    echo "-wobble                                 (wobble)"
    echo "-atm                                    (summer/62 or winter/61)"
    echo "-split_max                              (max number of split files)"
    echo ""
}

atm=""
zenith=""
wobble="all"
split_max="10"

while :; do
    case $1 in
        -h|-\?|--help)
            show_help
            exit
            ;;
        -zenith)
            zenith=$2
            shift
            ;;
        -wobble)
            wobble=$2
            shift
            ;;
        -atm)
            atm=$2
            shift
            ;;
        -split_max)
            split_max=$2
            shift
            ;;
        *)
            break
    esac
    shift
done

# shellcheck disable=SC1091,SC1090
source "util.sh"
# shellcheck disable=SC1091,SC1090
source "setupMC.sh"
# shellcheck disable=SC1091,SC1090
source "/afs/ifh.de/group/cta/scratch/prado/VTS/setEnv.sh" "v501_rd"

######################
# Processing arguments
atm=$(validate_atm "${atm}")
atm=$(get_atm_number "${atm}")
zenith=$(validate_zenith "${zenith}")

if [ "${wobble}" = "all" ]; then
    wobble_list="0.0 0.25 0.5 0.75 1.0 1.25 1.5 1.75 2.0"
else
    wobble_list="${wobble}"
fi

for wob in ${wobble_list}; do
    printf "Wobble %s\n" "${wob}"
    wob=$(validate_wobble "${wob}")

    $EVNDISPSYS/scripts/VTS/IRF.production.sh "CARE" "EVNDISP" "${zenith}" "${wob}" \
        "${split_max}" "V6" "${atm}" 
done

echo "subEvndisp DONE"